USE [master]
GO
CREATE LOGIN [Admin] WITH PASSWORD=N'123', DEFAULT_DATABASE=[DBPracticaRN], CHECK_EXPIRATION=OFF,
CHECK_POLICY=OFF
GO
USE [DBPracticaRN]
GO
CREATE USER [Admin] FOR LOGIN [Admin]
GO
USE [DBPracticaRN]
GO
ALTER ROLE [db_owner] ADD MEMBER [Admin]
GO